[repository]
name = "split-monitor-workspaces"
authors = ["Duckonaut", "zjeffer"]
commit_pins = [
    ["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "f7a306396da163422048fd38eecd92c68ce21e58"]  # 0.38.1
]

[split-monitor-workspaces]
description = "Split monitor workspaces"
authors = ["Duckonaut"]
output = "build/libsplit-monitor-workspaces.so"
build = [
    "meson setup build --wipe",
    "meson compile -C build",
]
